spring:
  application:
    name: registration-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/registrationdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8083}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9093}
  client:
    event-service:
      address: ${EVENT_SERVICE_GRPC_ADDRESS:static://localhost:9091}
      negotiation-type: plaintext
