apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: event-service-db
  namespace: event-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: event-service-db
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: /event-management/event-service/db-url
    - secretKey: DB_USERNAME
      remoteRef:
        key: /event-management/event-service/db-username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /event-management/event-service/db-password
