apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabase-db
  namespace: event-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: metabase-db
    creationPolicy: Owner
  data:
    - secretKey: MB_DB_HOST
      remoteRef:
        key: /event-management/metabase/db-host
    - secretKey: MB_DB_PORT
      remoteRef:
        key: /event-management/metabase/db-port
    - secretKey: MB_DB_DBNAME
      remoteRef:
        key: /event-management/metabase/db-dbname
    - secretKey: MB_DB_USER
      remoteRef:
        key: /event-management/metabase/db-user
    - secretKey: MB_DB_PASS
      remoteRef:
        key: /event-management/metabase/db-pass
    - secretKey: MB_ENCRYPTION_SECRET_KEY
      remoteRef:
        key: /event-management/metabase/encryption-key
