apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-service
  namespace: event-management
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::959740417723:role/event-service-irsa-role
