spring:
  application:
    name: program-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/programsdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9092}

server:
  port: ${SERVER_PORT:8082}
