server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /api/events/ {
        proxy_pass http://event-service:8081/api/events/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/sponsors {
        proxy_pass http://event-service:8081/api/sponsors;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/contact {
        proxy_pass http://event-service:8081/api/contact;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/speakers {
        proxy_pass http://program-service:8082/api/speakers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/sessions {
        proxy_pass http://program-service:8082/api/sessions;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/registrations {
        proxy_pass http://registration-service:8083/api/registrations;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/analytics {
        proxy_pass http://analytics-service:8085/api/analytics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
