spring:
  application:
    name: analytics-service

  datasource:
    url: ${DB_URL:jdbc:clickhouse://localhost:8123/analytics}
    username: ${DB_USERNAME:analytics}
    password: ${DB_PASSWORD:analytics123}
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

server:
  port: ${SERVER_PORT:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
